In [58]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity ='all'
%matplotlib inline
import sys
import tensorflow as tf

In [13]:
#tensors
3  #rank 0 tensor ,scaler with shape []
[1. ,2.,3.]  #rank 1, vector with shape[3]
[[1.,2.,3.], [4. ,5.,6.]]  #rank 2 with matrix shape[2,3]
[[[1.,2.,3.],[4., 5., 6.]]]  #rank 3 with shape[2,1,3]

3

[1.0, 2.0, 3.0]

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

[[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]]

In [ ]:
#Constant=fixed value tensor

In [26]:
node1=tf.constant(3.0, dtype=tf.float32)
node2=tf.constant(4.0)
print(node1,node2)

Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32)


In [23]:
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()

In [27]:
print(sess.run([node1, node2]))

[3.0, 4.0]


In [30]:
node3=tf.add(node1,node2)
print('node3',node3)
print(sess.run(node3))

node3 Tensor("Add:0", shape=(), dtype=float32)
7.0


In [31]:
node4=tf.subtract(node2,node1)
print(node4)
print(sess.run(node4))

Tensor("Sub:0", shape=(), dtype=float32)
1.0


In [35]:
x=tf.constant(4,shape=(1,1),dtype='float32')
print(x)
print(sess.run(x))

Tensor("Const_6:0", shape=(1, 1), dtype=float32)
[[4.]]


In [36]:
y=tf.constant([[1,2,3],[4,5,6]])
print(sess.run(y))

[[1 2 3]
 [4 5 6]]


In [40]:
a=tf.zeros((3,2))
b=tf.ones((3,3))   
c=tf.eye(3)       #identical matrix
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
a=tf.range(5)
print(sess.run(a))

[0 1 2 3 4]


In [46]:
#mathematical operation
x=tf.constant([9,8,7])
y=tf.constant([3,3,3])
print(sess.run(x+y))    #also use z=add(x,y)
print(sess.run(x-y))
print(sess.run(x*y))
print(sess.run(x/y))
print(sess.run(x**2))

[12 11 10]
[6 5 4]
[27 24 21]
[3.         2.66666667 2.33333333]
[81 64 49]


In [52]:
#indexing 
x=tf.constant([2,3,6,7,8,3,2,4,67,89,5,333])
print(sess.run(x[:]))
print(sess.run(x[1:]))
print(sess.run(x[1:6]))
print(sess.run(x[::2]))
print(sess.run(x[::-1]))

[  2   3   6   7   8   3   2   4  67  89   5 333]
[  3   6   7   8   3   2   4  67  89   5 333]
[3 6 7 8 3]
[ 2  6  8  2 67  5]
[333   5  89  67   4   2   3   8   7   6   3   2]


In [54]:
a=tf.constant([[1,2],[3,4],[5,6]])
print(sess.run(a[0]))
print(sess.run(a[0:2]))

[1 2]
[[1 2]
 [3 4]]


In [67]:
#placeholders=A graph can be parameterized to accept external inputs, known as placeholders
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b

In [63]:
print(sess.run(adder_node, {a:3, b:6.8}))
print(sess.run(adder_node, {a:[3,5],b:[9,8]}))

9.8
[12. 13.]


In [64]:
adder_triplet=adder_node*3
print(sess.run(adder_triplet, {a:7,b:65}))

216.0


In [65]:
#Variable

In [70]:
#Variables allow us to add trainable parameters to a graph.
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

w= tf.Variable([.3],dtype=tf.float32)
b=tf.Variable([-.3],dtype=tf.float32)
x = tf.placeholder(tf.float32)
linear_model=w*x+b

In [71]:
#Constants are initialized when you call tf.constant, and their value can never change. 
#By contrast, variables are not initialized when you call tf.Variable. To initialize 
#all the variables in a TensorFlow program, you must explicitly call a special 
#operation as follows

In [73]:
init= tf.global_variables_initializer()
sess.run(init)
print(sess.run(linear_model, {x:[1,2,3,4]}))

[0.         0.3        0.6        0.90000004]


In [75]:
#Complete Linear Regression model
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

#model parameter
w=tf.Variable([.3], dtype=tf.float32)
b=tf.Variable([-.3], dtype=tf.float32)
x=tf.placeholder(tf.float32)
linear_model=w*x+b
y=tf.placeholder(tf.float32)

#loss
loss=tf.reduce_sum(tf.square(linear_model - y))

#optimizer
optimizer=tf.train.GradientDescentOptimizer(0.01)
train=optimizer.minimize(loss)

#training_data
x_train=[1,2,3,4]
y_train=[0,-1,-2,-3]

#training_loop
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
for i in range(1000):
  sess.run(train, {x:x_train, y:y_train})

#evaluating training accuracy
curr_W,curr_b,curr_loss= sess.run([w, b, loss], {x:x_train, y:y_train})
print("W: %s b: %s loss: %s"%(curr_W, curr_b, curr_loss))

W: [-0.9999969] b: [0.9999908] loss: 5.6999738e-11
